name: Deploy API to PROD

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: prod

  merge-down:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run Merge-Down Action
        uses: bayer-int/tlp-actions/shared-actions/release-merge-down@v2
